services:
  - type: web
    name: ridesync-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: RIDESYNC_ENV
        value: production
      - key: RIDESYNC_DEBUG
        value: "false"
      - key: RIDESYNC_TIMEZONE
        value: Asia/Kolkata
      - key: RIDESYNC_COOKIE_SECURE
        value: "true"
      - key: RIDESYNC_TRUST_PROXY
        value: "true"
      - key: RIDESYNC_DB_HOST
        value: ridesync-db-ridesync-db.k.aivencloud.com
      - key: RIDESYNC_DB_PORT
        value: "26498"
      - key: RIDESYNC_DB_NAME
        value: defaultdb
      - key: RIDESYNC_DB_USER
        value: avnadmin
      - key: RIDESYNC_DB_PASSWORD
        sync: false
      - key: RIDESYNC_DOCUMENT_ENCRYPTION_KEY
        generateValue: true
      - key: RIDESYNC_REPAIR_LOG_KEY
        generateValue: true
      - key: RIDESYNC_METRICS_TOKEN
        generateValue: true
      - key: RIDESYNC_VERIFICATION_SERVICE_TOKEN
        generateValue: true
      - key: RIDESYNC_WS_SHARED_TOKEN
        generateValue: true
      - key: RIDESYNC_KYC_PROVIDER
        value: mock_compliance_provider
      - key: RIDESYNC_VERIFICATION_ASYNC
        value: "false"
      - key: RIDESYNC_VERIFICATION_INLINE_FALLBACK
        value: "true"

  - type: web
    name: ridesync-ws
    runtime: docker
    dockerfilePath: ./realtime/websocket-gateway/Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: RIDESYNC_WS_POLL_MS
        value: "1500"
      - key: RIDESYNC_WS_SHARED_TOKEN
        fromService:
          type: web
          name: ridesync-app
          envVarKey: RIDESYNC_WS_SHARED_TOKEN
      - key: RIDESYNC_DB_HOST
        value: ridesync-db-ridesync-db.k.aivencloud.com
      - key: RIDESYNC_DB_PORT
        value: "26498"
      - key: RIDESYNC_DB_NAME
        value: defaultdb
      - key: RIDESYNC_DB_USER
        value: avnadmin
      - key: RIDESYNC_DB_PASSWORD
        sync: false
