<?php
function ridesync_college_suggestions() {
    $colleges = [
        "A.J. Institute of Dental Sciences, Mangaluru",
        "A.J. Institute of Engineering and Technology, Mangaluru",
        "A.J. Institute of Management, Mangaluru",
        "A.J. Institute of Medical Sciences and Research Centre, Mangaluru",
        "A.J. Institute of Nursing Sciences, Mangaluru",
        "A.J. Institute of Speech and Hearing, Mangaluru",
        "A.J. Institute of Technology, Mangaluru",
        "Adarsha College, Bantwal",
        "AIMIT - St Aloysius Institute of Management and Information Technology, Mangaluru",
        "Aims First Grade College, Kadaba",
        "Akshaya College, Puttur",
        "Alva's College, Moodbidri",
        "Alva's College of Education, Moodbidri",
        "Alva's College of Naturopathy and Yogic Sciences, Moodbidri",
        "Alva's College of Nursing, Moodbidri",
        "Alva's College of Physical Education, Moodbidri",
        "Alva's Homoeopathic Medical College, Moodbidri",
        "Alva's Institute of Engineering and Technology, Moodbidri",
        "Ambika College, Puttur",
        "Ambika Maha Vidyalaya, Puttur",
        "Amrutha College, Padil, Mangaluru",
        "Amrutha College of Education, Padil, Mangaluru",
        "Anjuman First Grade College, Jokatte",
        "Anugraha First Grade College, Bantwal",
        "Anugraha Women's College, Kalladka",
        "Badriya First Grade College, Mangaluru",
        "Bearys Enviro Architecture Design School, Mangaluru",
        "Bearys Institute of Technology, Mangaluru",
        "Besant Evening College, Mangaluru",
        "Besant Women's College, Mangaluru",
        "Canara College, Mangaluru",
        "Canara Engineering College, Bantwal",
        "City College of Nursing, Mangaluru",
        "College of Fisheries, Mangaluru",
        "College of Teacher Education, Mangaluru",
        "Dr. K. Shivarama Karanth Government First Grade College, Bellare",
        "Dr. M.V. Shetty College of Education, Mangaluru",
        "Dr. M.V. Shetty College of Engineering, Moodbidri",
        "Dr. M.V. Shetty College of Nursing, Mangaluru",
        "Dr. P. Dayananda Pai - P. Satisha Pai Government First Grade College, Mangaluru",
        "Father Muller College of Allied Health Sciences, Mangaluru",
        "Father Muller College of Nursing, Mangaluru",
        "Father Muller Homoeopathic Medical College, Deralakatte",
        "Father Muller Medical College, Mangaluru",
        "Govinda Dasa College, Surathkal",
        "Government First Grade College, Bantwal",
        "Government First Grade College, Belthangady",
        "Government First Grade College, Haleyangadi",
        "Government First Grade College, Kavoor, Mangaluru",
        "Government First Grade College, Kanyana",
        "Government First Grade College, Mangaluru",
        "Government First Grade College, Mudipu",
        "Government First Grade College, Punjalkatte",
        "Government First Grade Evening College, Car Street, Mangaluru",
        "Government Women's First Grade College, Balmatta, Mangaluru",
        "Karnataka Polytechnic, Mangaluru",
        "Karavali College, Mangaluru",
        "Karavali College of Education, Mangaluru",
        "Karavali College of Pharmacy, Mangaluru",
        "Karavali Institute of Technology, Mangaluru",
        "Kukke Sri Subrahmanyeshwara College, Subrahmanya",
        "KVG Ayurveda Medical College, Sullia",
        "KVG College of Engineering, Sullia",
        "KVG Dental College and Hospital, Sullia",
        "KVG Medical College and Hospital, Sullia",
        "KVG Nursing College, Sullia",
        "LCR Indian Degree College, Bantwal",
        "Mangalore Academy of Professional Studies, Mangaluru",
        "Mangalore Institute of Fashion Technology, Mangaluru",
        "Mangalore Institute of Fire and Safety Engineering, Mangaluru",
        "Mangalore Institute of Technology and Engineering, Moodbidri",
        "Mangalore Marine College and Technology, Mangaluru",
        "Mangalore University, Konaje",
        "Manel Srinivas Nayak Institute of Management, Mangaluru",
        "MAPS Evening College, Mangaluru",
        "Medha College, Puttur",
        "Melkar Degree College, Bantwal",
        "Meridian College, Ullal",
        "Milagres College, Mangaluru",
        "Misba Women's College, Surathkal",
        "Moti Mahal College of Hotel Management, Mangaluru",
        "Nehru Memorial College, Sullia",
        "NITK Surathkal",
        "Nitte Institute of Architecture, Mangaluru",
        "Nitte Institute of Communication, Mangaluru",
        "Nitte Institute of Physiotherapy, Deralakatte",
        "Nitte Institute of Speech and Hearing, Deralakatte",
        "Nitte Institute of Tourism and Hospitality Studies, Mangaluru",
        "Nitte Usha Institute of Nursing Sciences, Deralakatte",
        "P.A. College of Engineering, Mangaluru",
        "P.A. First Grade College, Bantwal",
        "Padua College of Commerce and Management, Mangaluru",
        "Pana Institute of Undergraduate Studies, Bajpe",
        "Pompei College, Aikala",
        "Prasanna College of Education, Ujire",
        "Prasanna College of Engineering and Technology, Belthangady",
        "Roshni Nilaya School of Social Work, Mangaluru",
        "Sacred Heart College, Madanthyar",
        "Sahyadri College of Engineering and Management, Mangaluru",
        "Sapientia Bethany First Grade College, Nellyady",
        "Sarsa College of Arts and Science, Mangaluru",
        "Sarosh Institute of Hotel Administration, Mangaluru",
        "SDM College, Ujire",
        "SDM College of Business Management, Mangaluru",
        "SDM College of Education, Ujire",
        "SDM College of Naturopathy and Yogic Sciences, Ujire",
        "SDM Law College, Mangaluru",
        "SDM Post Graduate Centre for Management Studies and Research, Mangaluru",
        "SDM Institute of Technology, Ujire",
        "Sharada College, Mangaluru",
        "Shree Bharathi College, Mangaluru",
        "Shree Devi College, Mangaluru",
        "Shree Devi College of Fashion Design, Mangaluru",
        "Shree Devi College of Hotel Management, Mangaluru",
        "Shree Devi College of Information Science, Mangaluru",
        "Shree Devi College of Interior Design, Mangaluru",
        "Shree Devi College of Nursing, Mangaluru",
        "Shree Devi College of Pharmacy, Mangaluru",
        "Shree Devi Institute of Social Work, Mangaluru",
        "Shree Devi Institute of Technology, Mangaluru",
        "Silicon College of Advanced Studies, Mangaluru",
        "Srinivas College, Mangaluru",
        "Srinivas College of Education, Mangaluru",
        "Srinivas First Grade College, Mangaluru",
        "Srinivas Institute of Dental Sciences, Mangaluru",
        "Srinivas Institute of Medical Sciences and Research Centre, Mangaluru",
        "Srinivas Institute of Nursing Sciences, Mangaluru",
        "Srinivas Institute of Technology, Mangaluru",
        "Srinivas University, Mangaluru",
        "Sri Bhuvanendra College, Karkala",
        "Sri Dharmasthala Manjunatheshwara College, Ujire",
        "Sri Dhawala College, Moodbidri",
        "Sri Durgaparameshwari Temple First Grade College, Kateel",
        "Sri Gokarnatheshwara College, Mangaluru",
        "Sri Gokarnatheshwara College of Education, Mangaluru",
        "Sri Gurudeva First Grade College, Belthangady",
        "Sri Mahaveera College, Moodbidri",
        "Sri Narayanaguru First Grade College, Mangaluru",
        "Sri Niranjana Swamy First Grade College, Bajpe",
        "Sri Ram Kunjeshwara College, Ramakunja",
        "Sri Rama First Grade College, Kalladka",
        "Sri Ramakrishna College, Mangaluru",
        "Sri Sharada Women's College, Sullia",
        "Sri Venkatramana Swamy College, Bantwal",
        "St Agnes College, Mangaluru",
        "St Aloysius College, Mangaluru",
        "St Aloysius Institute of Education, Mangaluru",
        "St Ann's College of Education, Mangaluru",
        "St Antony College of Commerce, Naravi",
        "St Joseph Engineering College, Mangaluru",
        "St Philomena College, Puttur",
        "St Raymond's College, Vamanjoor",
        "Swasthika National School, Mangaluru",
        "Tejaswini College of Science and Therapy, Mangaluru",
        "Tippu Sulthan First Grade College, Ullal",
        "Trisha College of Commerce and Management, Mangaluru",
        "Trisha Evening College, Mangaluru",
        "University College, Mangaluru",
        "University Evening College, Mangaluru",
        "Vidyarashmi First Grade College, Puttur",
        "Vijaya College, Mulki",
        "Vikas First Grade College, Mangaluru",
        "Vivekananda College of Arts, Science and Commerce, Puttur",
        "Vivekananda College of Education, Puttur",
        "Vivekananda College of Engineering and Technology, Puttur",
        "Vivekananda Polytechnic, Puttur",
        "Yenepoya Dental College, Deralakatte",
        "Yenepoya Institute of Arts, Science, Commerce and Management, Mangaluru",
        "Yenepoya Institute of Technology, Moodbidri",
        "Yenepoya Medical College, Deralakatte",
        "Yenepoya Nursing College, Deralakatte",
        "Yenepoya University, Deralakatte",
    ];

    $colleges = array_values(array_unique($colleges));
    sort($colleges, SORT_NATURAL | SORT_FLAG_CASE);

    return $colleges;
}

function ridesync_render_college_datalist($id = 'college-suggestions') {
    echo '<datalist id="' . htmlspecialchars($id) . '">' . PHP_EOL;
    foreach (ridesync_college_suggestions() as $college) {
        echo '    <option value="' . htmlspecialchars($college) . '"></option>' . PHP_EOL;
    }
    echo '</datalist>' . PHP_EOL;
}
?>
